from src.structured_direction.classified_address_one import ClassifiedAddressOne

ADDRESS_LIST = [
#     ave 243 92a08 entre 92a y 94 la cumbre san miguel del padron la habana
ClassifiedAddressOne(principal_street=['243'],
                                          first_side_street=['92a',],
                                          second_side_street=['94'],
                                          locality=['la', 'cumbre'],
                                          municipality=['san', 'miguel', 'del', 'padron' ],
                                          province=['la', 'habana'],
                                          building=['92a08'],
                                          apartment=[],
                                      reserve_word=['ave', 'entre', 'y']),
#     calle reforma 11210 entre calle 13 y calle pastora reparto antonio maceo cerro la habana
ClassifiedAddressOne(principal_street=['reforma'],
                                          first_side_street=['13',],
                                          second_side_street=['pastora'],
                                          locality=['antonio', 'maceo'],
                                          municipality=['cerro',],
                                          province=['la', 'habana'],
                                          building=['11210'],
                                          apartment=[],
                                      reserve_word=['calle', 'entre', 'calle', 'y', 'calle', 'reparto']),
#     ave 35 edificio 221 apto 4 entre 246 y 250 la lisa la habana
ClassifiedAddressOne(principal_street=['35'],
                                          first_side_street=['246',],
                                          second_side_street=['250'],
                                          locality=[],
                                          municipality=['la', 'lisa'],
                                          province=['la', 'habana'],
                                          building=['221'],
                                          apartment=['4'],
                                      reserve_word=['ave', 'edificio', 'apto', 'entre', 'y' ]),
# avenida 45 10621 e entre 106 y 108 marianao la habana
ClassifiedAddressOne(principal_street=['45'],
                                          first_side_street=['106',],
                                          second_side_street=['108'],
                                          locality=[],
                                          municipality=['marianao',],
                                          province=['la', 'habana'],
                                          building=['10621'],
                                          apartment=['e'],
                                      reserve_word=['avenida', 'entre', 'y']),
# clavel 575 entre santa ana y concepcin cerro cerro la habana
ClassifiedAddressOne(principal_street=['575'],
                                          first_side_street=['santa', 'ana'],
                                          second_side_street=['concepcin'],
                                          locality=['cerro'],
                                          municipality=['cerro',],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['clavel', 'entre', 'y']),
# calzada vento esquina calle 3 edificio 7924 apto a reparto altahabana boyeros la habana
ClassifiedAddressOne(principal_street=['vento',],
                                          first_side_street=['3',],
                                          second_side_street=[],
                                          locality=['altahabana'],
                                          municipality=['boyeros',],
                                          province=['la', 'habana'],
                                          building=['7924'],
                                          apartment=['a'],
                                      reserve_word=['calzada', 'esquina', 'calle', 'edificio', 'apto', 'reparto']),
# avenida 31 4416 entre 44 y 46 apto 22 playa la habana
ClassifiedAddressOne(principal_street=['31'],
                                          first_side_street=['44',],
                                          second_side_street=['46'],
                                          locality=[],
                                          municipality=['playa',],
                                          province=['la', 'habana'],
                                          building=['4416'],
                                          apartment=['22'],
                                      reserve_word=['avenida', 'entre', 'y', 'apto']),
# calle 21 entre avenida 416 y avenida 418 edificio f6 apto 27 reparto peas altas, la habana del este, la habana
ClassifiedAddressOne(principal_street=['21'],
                                          first_side_street=['416',],
                                          second_side_street=['418'],
                                          locality=['peas', 'altas'],
                                          municipality=['la', 'habana', 'del', 'este'],
                                          province=['la', 'habana'],
                                          building=['f6'],
                                          apartment=['27'],
                                      reserve_word=['calle', 'entre', 'avenida', 'y', 'avenida', 'edificio', 'apto', 'reparto', ',', ',']),
# calle blanco 11706 altos entre b y c las granjas, cotorro, la habana
ClassifiedAddressOne(principal_street=['blanco'],
                                          first_side_street=['b',],
                                          second_side_street=['c'],
                                          locality=['las', 'granjas'],
                                          municipality=['cotorro',],
                                          province=['la', 'habana'],
                                          building=['11706'],
                                          apartment=[],
                                      reserve_word=['calle', 'altos', 'entre', 'y', ',', ',']),
# avenida guinera entre calle altura del rosario y calle d edif 1 apto 1b, reparto rosario,arroyo naranjo,la habana
ClassifiedAddressOne(principal_street=['guinera'],
                                          first_side_street=['altura', 'del', 'rosario'],
                                          second_side_street=['d'],
                                          locality=['rosario'],
                                          municipality=['arroyo', 'naranjo'],
                                          province=['la', 'habana'],
                                          building=['1'],
                                          apartment=['1b'],
                                      reserve_word=['avenida', 'entre', 'calle', 'y', 'calle', 'edif', 'apto', ',', 'reparto', ',', ',']),
# valle edif 11 apto 205 entre espada y hospital centro habana la habana
ClassifiedAddressOne(principal_street=['valle'],
                                          first_side_street=['espada',],
                                          second_side_street=['hospital'],
                                          locality=[],
                                          municipality=['centro', 'habana'],
                                          province=['la', 'habana'],
                                          building=['11'],
                                          apartment=['205'],
                                      reserve_word=['edif', 'apto', 'entre', 'y']),
# 253a entre 28 y 30 no 2801a apto 4 altos punta brava la lisa, la habana
ClassifiedAddressOne(principal_street=['253a'],
                                          first_side_street=['28',],
                                          second_side_street=['30'],
                                          locality=['punta', 'brava'],
                                          municipality=['la', 'lisa'],
                                          province=['la', 'habana'],
                                          building=['2801a'],
                                          apartment=['4'],
                                      reserve_word=['entre', 'y', 'no', 'apto', 'altos', ',']),
# calzada 10 de octubre entre calle alejandro ramirez y calle aguua dulce no 152 apto 1,cerro,la habana
ClassifiedAddressOne(principal_street=['10', 'de', 'octubre'],
                                          first_side_street=['alejandro', 'ramirez'],
                                          second_side_street=['aguua', 'dulce'],
                                          locality=[],
                                          municipality=['cerro',],
                                          province=['la', 'habana'],
                                          building=['152'],
                                          apartment=['1'],
                                      reserve_word=['calzada', 'entre', 'calle', 'y', 'calle', 'no', 'apto', ',', ',']),
# calle 245 entre ave 35 b y ave 35d, edificio 231 apto 13 la lisa, la habana
ClassifiedAddressOne(principal_street=['245'],
                                          first_side_street=['35', 'b'],
                                          second_side_street=['35d'],
                                          locality=[],
                                          municipality=['la', 'lisa'],
                                          province=['la', 'habana'],
                                          building=['231'],
                                          apartment=['13'],
                                      reserve_word=['calle', 'entre', 'ave', 'y', 'ave', ',', 'edificio', 'apto', ',']),
# calle 237 23704 entre calle 284 y calle 286 reparto inva boyeros la habana
ClassifiedAddressOne(principal_street=['237'],
                                          first_side_street=['284',],
                                          second_side_street=['286'],
                                          locality=['inva'],
                                          municipality=['boyeros',],
                                          province=['la', 'habana'],
                                          building=['23704'],
                                          apartment=[],
                                      reserve_word=['calle', 'entre', 'calle', 'y', 'calle', 'reparto']),
# calle ca ongo no 120 entre calle santa teresa y calle monasterio la habana cerro
ClassifiedAddressOne(principal_street=['ca', 'ongo'],
                                          first_side_street=['santa', 'teresa'],
                                          second_side_street=['monasterio'],
                                          locality=[],
                                          municipality=['cerro',],
                                          province=['la', 'habana'],
                                          building=['120'],
                                          apartment=[],
                                      reserve_word=['calle', 'no', 'entre', 'calle', 'y', 'calle']),
# calle arroyo 27 entre calle cristina y calle línea la habana vieja, la habana
ClassifiedAddressOne(principal_street=['arroyo'],
                                          first_side_street=['cristina',],
                                          second_side_street=['línea'],
                                          locality=[],
                                          municipality=['la', 'habana', 'vieja'],
                                          province=['la', 'habana'],
                                          building=['27'],
                                          apartment=[],
                                      reserve_word=['calle', 'entre', 'calle', 'y', 'calle', ',']),
# calle 224 e2 apto 311 entre 33 y 35 la coronela la liza, la habana
ClassifiedAddressOne(principal_street=['224'],
                                          first_side_street=['33',],
                                          second_side_street=['35'],
                                          locality=['la', 'coronela'],
                                          municipality=['la', 'liza'],
                                          province=['la', 'habana'],
                                          building=['e2'],
                                          apartment=['311'],
                                      reserve_word=['calle', 'apto', 'entre', 'y', ',']),
# alfredo lopez entre facciolo y gutember, no 4 apto 2, capri, arroyo naranjo, la habana
ClassifiedAddressOne(principal_street=['alfredo', 'lopez'],
                                          first_side_street=['facciolo',],
                                          second_side_street=['gutember'],
                                          locality=['capri'],
                                          municipality=['arroyo', 'naranjo'],
                                          province=['la', 'habana'],
                                          building=['4'],
                                          apartment=['2'],
                                      reserve_word=['entre', 'y', ',', 'no', 'apto', ',', ',', ',']),
# calle 383 entre calle 174 y calle 176 edif 17404 apto 16 reparto mulgoba boyeros la habana
ClassifiedAddressOne(principal_street=['383'],
                                          first_side_street=['174',],
                                          second_side_street=['176'],
                                          locality=['mulgoba'],
                                          municipality=['boyeros',],
                                          province=['la', 'habana'],
                                          building=['17404'],
                                          apartment=['16'],
                                      reserve_word=['calle', 'entre', 'calle', 'y', 'calle', 'edif', 'apto', 'reparto']),
# calle ursula 115 apto 4 entre calle gelabert y calle revolucion reparto sevillano diez de octubre, la habana
ClassifiedAddressOne(principal_street=['ursula'],
                                          first_side_street=['gelabert',],
                                          second_side_street=['revolucion'],
                                          locality=['sevillano'],
                                          municipality=['diez', 'de', 'octubre'],
                                          province=['la', 'habana'],
                                          building=['115'],
                                          apartment=['4'],
                                      reserve_word=['calle', 'apto', 'entre', 'calle', 'y', 'calle', 'reparto', ',']),
# cardenas entre gloria y mision la habana vieja, la habana
ClassifiedAddressOne(principal_street=['cardenas'],
                                          first_side_street=['gloria',],
                                          second_side_street=['mision'],
                                          locality=[''],
                                          municipality=['la', 'habana', 'vieja'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['entre', 'y', ',']),
# calle reyes entre c y altarriba, barrio lawton, diez de octubre, la habana
ClassifiedAddressOne(principal_street=['reyes'],
                                          first_side_street=['c',],
                                          second_side_street=['altarriba'],
                                          locality=['lawton'],
                                          municipality=['diez', 'de', 'octubre'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['calle', 'entre', 'y', ',', 'barrio', ',', ',']),
# 31 entre 74 y 76 buena vista, playa, la habana
ClassifiedAddressOne(principal_street=['31'],
                                          first_side_street=['74',],
                                          second_side_street=['76'],
                                          locality=['buena', 'vista'],
                                          municipality=['playa',],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['entre', 'y', ',', ',']),
# calle san rafael entre mazon y ronda, plaza de la revolución, la habana
ClassifiedAddressOne(principal_street=['san', 'rafael'],
                                          first_side_street=['mazon',],
                                          second_side_street=['ronda'],
                                          locality=[],
                                          municipality=['plaza', 'de', 'la', 'revolución'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['calle', 'entre', 'y', ',', ',']),
# florencia entre perkins y mayor, la fernanda, san miguel del padron, la habana
ClassifiedAddressOne(principal_street=['florencia'],
                                          first_side_street=['perkins',],
                                          second_side_street=['mayor'],
                                          locality=['la', 'fernanda'],
                                          municipality=['san', 'miguel', 'del', 'padron'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['entre',  'y', ',', ',', ',']),
# coyula entre pallares y cristobal de la guardia, guanabacoa, la habana
ClassifiedAddressOne(principal_street=['coyula'],
                                          first_side_street=['pallares',],
                                          second_side_street=['cristobal', 'de', 'la', 'guardia'],
                                          locality=[''],
                                          municipality=['guanabacoa',],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['entre', 'y', ',', ',']),
# 86 # 909 e / 11 y 9a, playa, la habana
ClassifiedAddressOne(principal_street=['86'],
                                          first_side_street=['11',],
                                          second_side_street=['9a'],
                                          locality=[''],
                                          municipality=['playa',],
                                          province=['la', 'habana'],
                                          building=['909'],
                                          apartment=[],
                                      reserve_word=['#', 'e', '/', 'y', ',', ',']),
# calle vento # 9519 e/ calle 6 y calle 10, altahabana, boyeros la habana
ClassifiedAddressOne(principal_street=['vento'],
                                          first_side_street=['6',],
                                          second_side_street=['10'],
                                          locality=['altahabana'],
                                          municipality=['boyeros',],
                                          province=['la', 'habana'],
                                          building=['9519'],
                                          apartment=[],
                                      reserve_word=['calle', '#', 'e', '/', 'calle', 'y', 'calle', ',', ',']),
# valle edif 11 apto 205 entre espada y hospital centro habana la habana
ClassifiedAddressOne(principal_street=['valle'],
                                          first_side_street=['espada',],
                                          second_side_street=['hospital'],
                                          locality=[],
                                          municipality=['centro', 'habana'],
                                          province=['la', 'habana'],
                                          building=['11'],
                                          apartment=['205'],
                                      reserve_word=['edif', 'apto', 'entre', 'y']),
# pasaje infante e / mayía rodrígez y goicuría, santo suárez, diez de octubre, la habana
ClassifiedAddressOne(principal_street=['infante'],
                                          first_side_street=['mayía', 'rodrígez'],
                                          second_side_street=['goicuría'],
                                          locality=['santo', 'suárez'],
                                          municipality=['diez', 'de', 'octubre'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['pasaje', 'e', '/', ',', ',', ',']),
# calle campanario e/ calle concordia y calle virtudes edificio 202 apto 3, centro habana, la habana
ClassifiedAddressOne(principal_street=['campanario'],
                                          first_side_street=['concordia',],
                                          second_side_street=['virtudes'],
                                          locality=[],
                                          municipality=['centro', 'habana'],
                                          province=['la', 'habana'],
                                          building=['202'],
                                          apartment=['3'],
                                      reserve_word=['calle', 'e/', 'calle', 'y', 'calle', 'edificio', 'apto', ',', ',']),
# calle trebol, boyeros, la habana
ClassifiedAddressOne(principal_street=['trebol'],
                                          first_side_street=['',],
                                          second_side_street=[''],
                                          locality=[],
                                          municipality=['boyeros',],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['calle', ',', ',']),
# clle san pedro  # 709 apto 12 y h e/ calle hidalgo y calle estancia plaza de la revolucion, la habana
ClassifiedAddressOne(principal_street=['san', 'pedro'],
                                          first_side_street=['hidalgo',],
                                          second_side_street=['estancia'],
                                          locality=[],
                                          municipality=['plaza', 'de', 'la', 'revolucion'],
                                          province=['la', 'habana'],
                                          building=['709'],
                                          apartment=['12', 'y', 'h'],
                                      reserve_word=['clle', '#', 'apto', 'e/', 'calle', 'y', 'calle', ',']),
# obrapía 357 entre habana y compostela, la habana vieja, la habana
ClassifiedAddressOne(principal_street=['obrapía'],
                                          first_side_street=['habana',],
                                          second_side_street=['compostela'],
                                          locality=[],
                                          municipality=['la', 'habana', 'vieja'],
                                          province=['la', 'habana'],
                                          building=['357'],
                                          apartment=[],
                                      reserve_word=['entre', 'y', ',', ',']),
# j # 515 entre calzada y 9, plaza de la revolucion, la habana
ClassifiedAddressOne(principal_street=['j'],
                                          first_side_street=['calzada',],
                                          second_side_street=['9'],
                                          locality=[],
                                          municipality=['plaza', 'de', 'la', 'revolucion'],
                                          province=['la', 'habana'],
                                          building=['515'],
                                          apartment=[],
                                      reserve_word=['#', 'entre', 'y', ',', ',']),
# n # 11115, apto 25 / e y 3ra, altahabana, boyeros, la habana
ClassifiedAddressOne(principal_street=['n'],
                                          first_side_street=['e', ],
                                          second_side_street=['3ra'],
                                          locality=['altahabana'],
                                          municipality=['boyeros',],
                                          province=['la', 'habana'],
                                          building=['11115'],
                                          apartment=['25'],
                                      reserve_word=['#', ',', 'apto', '/', 'y', ',', ',', ',']),
# avenida 37 # 3422 bajos / calle 34 y calle 36, reparto la sierra, la lisa, la habana
ClassifiedAddressOne(principal_street=['37'],
                                          first_side_street=['34',],
                                          second_side_street=['36'],
                                          locality=['la', 'sierra'],
                                          municipality=['la', 'lisa'],
                                          province=['la', 'habana'],
                                          building=['3422'],
                                          apartment=[],
                                      reserve_word=['avenida', '#', 'bajos', '/', 'calle', 'y', 'calle', ',', 'reparto', ',', ',', ]),
# calle 1 # 9814 e/ calle final y calle paz, reparto tejas, san miguel del padron, la habana
ClassifiedAddressOne(principal_street=['1'],
                                          first_side_street=['final',],
                                          second_side_street=['paz'],
                                          locality=['tejas'],
                                          municipality=['san', 'miguel', 'del', 'padron'],
                                          province=['la', 'habana'],
                                          building=['9814'],
                                          apartment=[],
                                      reserve_word=['calle', '#', 'e/', 'calle', 'y', 'calle', ',', 'reparto', ',', ',']),
# avenida 5 no 24042 e/ ca 242 y ca 240, reparto santa fernanda, playa, la habana
ClassifiedAddressOne(principal_street=['5'],
                                          first_side_street=['242',],
                                          second_side_street=['240'],
                                          locality=['santa', 'fernanda'],
                                          municipality=['playa',],
                                          province=['la', 'habana'],
                                          building=['24042'],
                                          apartment=[],
                                      reserve_word=['avenida', 'no', 'e/', 'ca', 'y', 'ca', ',', 'reparto', ',', ',']),
# e e/ 23 y 25, plza de la revolucion, la habana
ClassifiedAddressOne(principal_street=['e'],
                                          first_side_street=['23',],
                                          second_side_street=['25'],
                                          locality=[],
                                          municipality=['plza', 'de', 'la', 'revolucion'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',']),
# calle parque esq avenida carolina, reparto carolina, san miguel del padron, la habana
ClassifiedAddressOne(principal_street=['parque'],
                                          first_side_street=['carolina',],
                                          second_side_street=[],
                                          locality=['carolina'],
                                          municipality=['san', 'miguel', 'del', 'padron'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['calle', 'esq', 'avenida', ',', 'reparto', ',', ',']),
# calle san juan, guanabacoa, ciudad de la habana
ClassifiedAddressOne(principal_street=['san', 'juan'],
                                          first_side_street=[],
                                          second_side_street=[],
                                          locality=[],
                                          municipality=['guanabacoa',],
                                          province=['ciudad', 'de', 'la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['calle', ',', ',']),
# calle el brinco, santa fe, guanabacoa, ciudad de la habana
ClassifiedAddressOne(principal_street=['el', 'brinco'],
                                          first_side_street=[],
                                          second_side_street=[],
                                          locality=['santa', 'fe'],
                                          municipality=['guanabacoa',],
                                          province=['ciudad', 'de', 'la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['calle', ',', ',', ',']),
# san juan, guanabacoa, reparto bacuranao, ciudad de la habana
ClassifiedAddressOne(principal_street=['san', 'juan'],
                                          first_side_street=[],
                                          second_side_street=[],
                                          locality=['bacuranao'],
                                          municipality=['guanabacoa',],
                                          province=['ciudad', 'de', 'la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['reparto', ',', ',', ',']),
# esquina 3a y primera e, cuatro caminos, bejucal, la habana
ClassifiedAddressOne(principal_street=['3a'],
                                          first_side_street=['primera', 'e'],
                                          second_side_street=[],
                                          locality=['cuatro', 'caminos'],
                                          municipality=['bejucal',],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['esquina', 'y', ',', ',', ',']),
# maceo esquina 49 san jose de las lajas, la habana
ClassifiedAddressOne(principal_street=['maceo'],
                                          first_side_street=['49'],
                                          second_side_street=[],
                                          locality=[],
                                          municipality=['san', 'de', 'las', 'lajas'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['esquina', ',']),
# calle sayas esq sandaio camblort san antonio de los baños, la habana
ClassifiedAddressOne(principal_street=['sayas'],
                                          first_side_street=['sandaio', 'camblort'],
                                          second_side_street=[],
                                          locality=[],
                                          municipality=['san', 'antonio', 'de', 'los', 'baños'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['calle', 'esq', ',']),

]