from src.structured_direction.classified_address_one import ClassifiedAddressOne
import tensorflow as tf
# Assert Case
# y_pred = [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
# y_real = [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

# Fail Case
# y_pred = [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
# y_real = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]

# Test Case
y_pred = [0.0973835886, 0.0959317908, 0.0735085383, 0.0930648819, 0.0859329849, 0.0832466409, 0.577864632, 0.501, 0.0859992132, 0.0921353698]
y_real = [0, 0, 0, 0, 0, 0, 0, 1, 0, 0]

VP = tf.keras.metrics.TruePositives()
VP.update_state(y_real, y_pred)
VP = VP.result().numpy()

VN = tf.keras.metrics.TrueNegatives()
VN.update_state(y_real, y_pred)
VN = VN.result().numpy()

FP = tf.keras.metrics.FalsePositives()
FP.update_state(y_real, y_pred)
FP = FP.result().numpy()

FN = tf.keras.metrics.FalseNegatives()
FN.update_state(y_real, y_pred)
FN = FN.result().numpy()


print('Caso de acierto en la prediccion.')
print('VP = ', VP)
print('VN = ', VN)
print('FP = ', FP)
print('FN = ', FN)

# Precision
precision = tf.keras.metrics.Precision(thresholds=0)
precision.update_state(y_real, y_pred)
precision = precision.result().numpy()

recall = tf.keras.metrics.Recall(thresholds=0)
recall.update_state(y_real, y_pred)
recall = recall.result().numpy()

print('Metricas: ')
print('Precision: ', precision)
print('Recall: ', recall)


ADDRESS_LIST = [
#     ave 243 92a08 entre 92a y 94 la cumbre san miguel del padron la habana
ClassifiedAddressOne(principal_street=['243'],
                                          first_side_street=['92a',],
                                          second_side_street=['94'],
                                          locality=['la', 'cumbre'],
                                          municipality=['san', 'miguel', 'del', 'padron' ],
                                          province=['la', 'habana'],
                                          building=['92a08'],
                                          apartment=[],
                                      reserve_word=['ave', 'entre', 'y']),
#     calle reforma 11210 entre calle 13 y calle pastora reparto antonio maceo cerro la habana
ClassifiedAddressOne(principal_street=['reforma'],
                                          first_side_street=['13',],
                                          second_side_street=['pastora'],
                                          locality=['antonio', 'maceo'],
                                          municipality=['cerro',],
                                          province=['la', 'habana'],
                                          building=['11210'],
                                          apartment=[],
                                      reserve_word=['calle', 'entre', 'calle', 'y', 'calle', 'reparto']),
#     ave 35 edificio 221 apto 4 entre 246 y 250 la lisa la habana
ClassifiedAddressOne(principal_street=['35'],
                                          first_side_street=['246',],
                                          second_side_street=['250'],
                                          locality=[],
                                          municipality=['la', 'lisa'],
                                          province=['la', 'habana'],
                                          building=['221'],
                                          apartment=['4'],
                                      reserve_word=['ave', 'edificio', 'apto', 'entre', 'y' ]),
# avenida 45 10621 e entre 106 y 108 marianao la habana
ClassifiedAddressOne(principal_street=['45'],
                                          first_side_street=['106',],
                                          second_side_street=['108'],
                                          locality=[],
                                          municipality=['marianao',],
                                          province=['la', 'habana'],
                                          building=['10621'],
                                          apartment=['e'],
                                      reserve_word=['avenida', 'entre', 'y']),
# clavel 575 entre santa ana y concepcin cerro cerro la habana
ClassifiedAddressOne(principal_street=['clavel'],
                                          first_side_street=['santa', 'ana'],
                                          second_side_street=['concepcin'],
                                          locality=['cerro'],
                                          municipality=['cerro',],
                                          province=['la', 'habana'],
                                          building=['575'],
                                          apartment=[],
                                      reserve_word=['entre', 'y']),
# calzada vento esquina calle 3 edificio 7924 apto a reparto altahabana boyeros la habana
ClassifiedAddressOne(principal_street=['vento',],
                                          first_side_street=['3',],
                                          second_side_street=[],
                                          locality=['altahabana'],
                                          municipality=['boyeros',],
                                          province=['la', 'habana'],
                                          building=['7924'],
                                          apartment=['a'],
                                      reserve_word=['calzada', 'esquina', 'calle', 'edificio', 'apto', 'reparto']),
# avenida 31 4416 entre 44 y 46 apto 22 playa la habana
ClassifiedAddressOne(principal_street=['31'],
                                          first_side_street=['44',],
                                          second_side_street=['46'],
                                          locality=[],
                                          municipality=['playa',],
                                          province=['la', 'habana'],
                                          building=['4416'],
                                          apartment=['22'],
                                      reserve_word=['avenida', 'entre', 'y', 'apto']),
# calle 21 entre avenida 416 y avenida 418 edificio f6 apto 27 reparto peas altas, la habana del este, la habana
ClassifiedAddressOne(principal_street=['21'],
                                          first_side_street=['416',],
                                          second_side_street=['418'],
                                          locality=['peas', 'altas'],
                                          municipality=['la', 'habana', 'del', 'este'],
                                          province=['la', 'habana'],
                                          building=['f6'],
                                          apartment=['27'],
                                      reserve_word=['calle', 'entre', 'avenida', 'y', 'avenida', 'edificio', 'apto', 'reparto', ',', ',']),
# calle blanco 11706 altos entre b y c las granjas, cotorro, la habana
ClassifiedAddressOne(principal_street=['blanco'],
                                          first_side_street=['b',],
                                          second_side_street=['c'],
                                          locality=['las', 'granjas'],
                                          municipality=['cotorro',],
                                          province=['la', 'habana'],
                                          building=['11706'],
                                          apartment=[],
                                      reserve_word=['calle', 'altos', 'entre', 'y', ',', ',']),
# avenida guinera entre calle altura del rosario y calle d edif 1 apto 1b, reparto rosario,arroyo naranjo,la habana
ClassifiedAddressOne(principal_street=['guinera'],
                                          first_side_street=['altura', 'del', 'rosario'],
                                          second_side_street=['d'],
                                          locality=['rosario'],
                                          municipality=['arroyo', 'naranjo'],
                                          province=['la', 'habana'],
                                          building=['1'],
                                          apartment=['1b'],
                                      reserve_word=['avenida', 'entre', 'calle', 'y', 'calle', 'edif', 'apto', ',', 'reparto', ',', ',']),
# valle edif 11 apto 205 entre espada y hospital centro habana la habana
ClassifiedAddressOne(principal_street=['valle'],
                                          first_side_street=['espada',],
                                          second_side_street=['hospital'],
                                          locality=[],
                                          municipality=['centro', 'habana'],
                                          province=['la', 'habana'],
                                          building=['11'],
                                          apartment=['205'],
                                      reserve_word=['edif', 'apto', 'entre', 'y']),
# 253a entre 28 y 30 no 2801a apto 4 altos punta brava la lisa, la habana
ClassifiedAddressOne(principal_street=['253a'],
                                          first_side_street=['28',],
                                          second_side_street=['30'],
                                          locality=['punta', 'brava'],
                                          municipality=['la', 'lisa'],
                                          province=['la', 'habana'],
                                          building=['2801a'],
                                          apartment=['4'],
                                      reserve_word=['entre', 'y', 'no', 'apto', 'altos', ',']),
# calzada 10 de octubre entre calle alejandro ramirez y calle aguua dulce no 152 apto 1,cerro,la habana
ClassifiedAddressOne(principal_street=['10', 'de', 'octubre'],
                                          first_side_street=['alejandro', 'ramirez'],
                                          second_side_street=['aguua', 'dulce'],
                                          locality=[],
                                          municipality=['cerro',],
                                          province=['la', 'habana'],
                                          building=['152'],
                                          apartment=['1'],
                                      reserve_word=['calzada', 'entre', 'calle', 'y', 'calle', 'no', 'apto', ',', ',']),
# calle 245 entre ave 35 b y ave 35d, edificio 231 apto 13 la lisa, la habana
ClassifiedAddressOne(principal_street=['245'],
                                          first_side_street=['35', 'b'],
                                          second_side_street=['35d'],
                                          locality=[],
                                          municipality=['la', 'lisa'],
                                          province=['la', 'habana'],
                                          building=['231'],
                                          apartment=['13'],
                                      reserve_word=['calle', 'entre', 'ave', 'y', 'ave', ',', 'edificio', 'apto', ',']),
# calle 237 23704 entre calle 284 y calle 286 reparto inva boyeros la habana
ClassifiedAddressOne(principal_street=['237'],
                                          first_side_street=['284',],
                                          second_side_street=['286'],
                                          locality=['inva'],
                                          municipality=['boyeros',],
                                          province=['la', 'habana'],
                                          building=['23704'],
                                          apartment=[],
                                      reserve_word=['calle', 'entre', 'calle', 'y', 'calle', 'reparto']),
# calle ca ongo no 120 entre calle santa teresa y calle monasterio la habana cerro
ClassifiedAddressOne(principal_street=['ca', 'ongo'],
                                          first_side_street=['santa', 'teresa'],
                                          second_side_street=['monasterio'],
                                          locality=[],
                                          municipality=['cerro',],
                                          province=['la', 'habana'],
                                          building=['120'],
                                          apartment=[],
                                      reserve_word=['calle', 'no', 'entre', 'calle', 'y', 'calle']),
# calle arroyo 27 entre calle cristina y calle línea la habana vieja, la habana
ClassifiedAddressOne(principal_street=['arroyo'],
                                          first_side_street=['cristina',],
                                          second_side_street=['línea'],
                                          locality=[],
                                          municipality=['la', 'habana', 'vieja'],
                                          province=['la', 'habana'],
                                          building=['27'],
                                          apartment=[],
                                      reserve_word=['calle', 'entre', 'calle', 'y', 'calle', ',']),
# calle 224 e2 apto 311 entre 33 y 35 la coronela la liza, la habana
ClassifiedAddressOne(principal_street=['224'],
                                          first_side_street=['33',],
                                          second_side_street=['35'],
                                          locality=['la', 'coronela'],
                                          municipality=['la', 'liza'],
                                          province=['la', 'habana'],
                                          building=['e2'],
                                          apartment=['311'],
                                      reserve_word=['calle', 'apto', 'entre', 'y', ',']),
# alfredo lopez entre facciolo y gutember, no 4 apto 2, capri, arroyo naranjo, la habana
ClassifiedAddressOne(principal_street=['alfredo', 'lopez'],
                                          first_side_street=['facciolo',],
                                          second_side_street=['gutember'],
                                          locality=['capri'],
                                          municipality=['arroyo', 'naranjo'],
                                          province=['la', 'habana'],
                                          building=['4'],
                                          apartment=['2'],
                                      reserve_word=['entre', 'y', ',', 'no', 'apto', ',', ',', ',']),
# calle 383 entre calle 174 y calle 176 edif 17404 apto 16 reparto mulgoba boyeros la habana
ClassifiedAddressOne(principal_street=['383'],
                                          first_side_street=['174',],
                                          second_side_street=['176'],
                                          locality=['mulgoba'],
                                          municipality=['boyeros',],
                                          province=['la', 'habana'],
                                          building=['17404'],
                                          apartment=['16'],
                                      reserve_word=['calle', 'entre', 'calle', 'y', 'calle', 'edif', 'apto', 'reparto']),
# calle ursula 115 apto 4 entre calle gelabert y calle revolucion reparto sevillano diez de octubre, la habana
ClassifiedAddressOne(principal_street=['ursula'],
                                          first_side_street=['gelabert',],
                                          second_side_street=['revolucion'],
                                          locality=['sevillano'],
                                          municipality=['diez', 'de', 'octubre'],
                                          province=['la', 'habana'],
                                          building=['115'],
                                          apartment=['4'],
                                      reserve_word=['calle', 'apto', 'entre', 'calle', 'y', 'calle', 'reparto', ',']),
# cardenas entre gloria y mision la habana vieja, la habana
ClassifiedAddressOne(principal_street=['cardenas'],
                                          first_side_street=['gloria',],
                                          second_side_street=['mision'],
                                          locality=[''],
                                          municipality=['la', 'habana', 'vieja'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['entre', 'y', ',']),
# calle reyes entre c y altarriba, barrio lawton, diez de octubre, la habana
ClassifiedAddressOne(principal_street=['reyes'],
                                          first_side_street=['c',],
                                          second_side_street=['altarriba'],
                                          locality=['lawton'],
                                          municipality=['diez', 'de', 'octubre'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['calle', 'entre', 'y', ',', 'barrio', ',', ',']),
# 31 entre 74 y 76 buena vista, playa, la habana
ClassifiedAddressOne(principal_street=['31'],
                                          first_side_street=['74',],
                                          second_side_street=['76'],
                                          locality=['buena', 'vista'],
                                          municipality=['playa',],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['entre', 'y', ',', ',']),
# calle san rafael entre mazon y ronda, plaza de la revolución, la habana
ClassifiedAddressOne(principal_street=['san', 'rafael'],
                                          first_side_street=['mazon',],
                                          second_side_street=['ronda'],
                                          locality=[],
                                          municipality=['plaza', 'de', 'la', 'revolucion'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['calle', 'entre', 'y', ',', ',']),
# florencia entre perkins y mayor, la fernanda, san miguel del padron, la habana
ClassifiedAddressOne(principal_street=['florencia'],
                                          first_side_street=['perkins',],
                                          second_side_street=['mayor'],
                                          locality=['la', 'fernanda'],
                                          municipality=['san', 'miguel', 'del', 'padron'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['entre',  'y', ',', ',', ',']),
# coyula entre pallares y cristobal de la guardia, guanabacoa, la habana
ClassifiedAddressOne(principal_street=['coyula'],
                                          first_side_street=['pallares',],
                                          second_side_street=['cristobal', 'de', 'la', 'guardia'],
                                          locality=[''],
                                          municipality=['guanabacoa',],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['entre', 'y', ',', ',']),
# 86 # 909 e / 11 y 9a, playa, la habana
ClassifiedAddressOne(principal_street=['86'],
                                          first_side_street=['11',],
                                          second_side_street=['9a'],
                                          locality=[''],
                                          municipality=['playa',],
                                          province=['la', 'habana'],
                                          building=['909'],
                                          apartment=[],
                                      reserve_word=['#', 'e', '/', 'y', ',', ',']),
# calle vento # 9519 e/ calle 6 y calle 10, altahabana, boyeros la habana
ClassifiedAddressOne(principal_street=['vento'],
                                          first_side_street=['6',],
                                          second_side_street=['10'],
                                          locality=['altahabana'],
                                          municipality=['boyeros',],
                                          province=['la', 'habana'],
                                          building=['9519'],
                                          apartment=[],
                                      reserve_word=['calle', '#', 'e/', 'calle', 'y', 'calle', ',', ',']),
# pasaje infante e / mayía rodrígez y goicuría, santo suárez, diez de octubre, la habana
ClassifiedAddressOne(principal_street=['infante'],
                                          first_side_street=['mayía', 'rodrígez'],
                                          second_side_street=['goicuría'],
                                          locality=['santo', 'suárez'],
                                          municipality=['diez', 'de', 'octubre'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['pasaje', 'e', '/', ',', ',', ',']),
# calle campanario e/ calle concordia y calle virtudes edificio 202 apto 3, centro habana, la habana
ClassifiedAddressOne(principal_street=['campanario'],
                                          first_side_street=['concordia',],
                                          second_side_street=['virtudes'],
                                          locality=[],
                                          municipality=['centro', 'habana'],
                                          province=['la', 'habana'],
                                          building=['202'],
                                          apartment=['3'],
                                      reserve_word=['calle', 'e/', 'calle', 'y', 'calle', 'edificio', 'apto', ',', ',']),
# calle trebol, boyeros, la habana
ClassifiedAddressOne(principal_street=['trebol'],
                                          first_side_street=['',],
                                          second_side_street=[''],
                                          locality=[],
                                          municipality=['boyeros',],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['calle', ',', ',']),
# clle san pedro  # 709 apto 12 y h e/ calle hidalgo y calle estancia plaza de la revolucion, la habana
ClassifiedAddressOne(principal_street=['san', 'pedro'],
                                          first_side_street=['hidalgo',],
                                          second_side_street=['estancia'],
                                          locality=[],
                                          municipality=['plaza', 'de', 'la', 'revolucion'],
                                          province=['la', 'habana'],
                                          building=['709'],
                                          apartment=['12', 'y', 'h'],
                                      reserve_word=['clle', '#', 'apto', 'e/', 'calle', 'y', 'calle', ',']),
# obrapía 357 entre habana y compostela, la habana vieja, la habana
ClassifiedAddressOne(principal_street=['obrapia'],
                                          first_side_street=['habana',],
                                          second_side_street=['compostela'],
                                          locality=[],
                                          municipality=['la', 'habana', 'vieja'],
                                          province=['la', 'habana'],
                                          building=['357'],
                                          apartment=[],
                                      reserve_word=['entre', 'y', ',', ',']),
# j # 515 entre calzada y 9, plaza de la revolucion, la habana
ClassifiedAddressOne(principal_street=['j'],
                                          first_side_street=['calzada',],
                                          second_side_street=['9'],
                                          locality=[],
                                          municipality=['plaza', 'de', 'la', 'revolucion'],
                                          province=['la', 'habana'],
                                          building=['515'],
                                          apartment=[],
                                      reserve_word=['#', 'entre', 'y', ',', ',']),
# n # 11115, apto 25 / e y 3ra, altahabana, boyeros, la habana
ClassifiedAddressOne(principal_street=['n'],
                                          first_side_street=['e', ],
                                          second_side_street=['3ra'],
                                          locality=['altahabana'],
                                          municipality=['boyeros',],
                                          province=['la', 'habana'],
                                          building=['11115'],
                                          apartment=['25'],
                                      reserve_word=['#', ',', 'apto', '/', 'y', ',', ',', ',']),
# avenida 37 # 3422 bajos / calle 34 y calle 36, reparto la sierra, la lisa, la habana
ClassifiedAddressOne(principal_street=['37'],
                                          first_side_street=['34',],
                                          second_side_street=['36'],
                                          locality=['la', 'sierra'],
                                          municipality=['la', 'lisa'],
                                          province=['la', 'habana'],
                                          building=['3422'],
                                          apartment=[],
                                      reserve_word=['avenida', '#', 'bajos', '/', 'calle', 'y', 'calle', ',', 'reparto', ',', ',', ]),
# calle 1 # 9814 e/ calle final y calle paz, reparto tejas, san miguel del padron, la habana
ClassifiedAddressOne(principal_street=['1'],
                                          first_side_street=['final',],
                                          second_side_street=['paz'],
                                          locality=['tejas'],
                                          municipality=['san', 'miguel', 'del', 'padron'],
                                          province=['la', 'habana'],
                                          building=['9814'],
                                          apartment=[],
                                      reserve_word=['calle', '#', 'e/', 'calle', 'y', 'calle', ',', 'reparto', ',', ',']),
# avenida 5 no 24042 e/ ca 242 y ca 240, reparto santa fernanda, playa, la habana
ClassifiedAddressOne(principal_street=['5'],
                                          first_side_street=['242',],
                                          second_side_street=['240'],
                                          locality=['santa', 'fernanda'],
                                          municipality=['playa',],
                                          province=['la', 'habana'],
                                          building=['24042'],
                                          apartment=[],
                                      reserve_word=['avenida', 'no', 'e/', 'ca', 'y', 'ca', ',', 'reparto', ',', ',']),
# e e/ 23 y 25, plza de la revolucion, la habana
ClassifiedAddressOne(principal_street=['e'],
                                          first_side_street=['23',],
                                          second_side_street=['25'],
                                          locality=[],
                                          municipality=['plza', 'de', 'la', 'revolucion'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',']),
# calle parque esq avenida carolina, reparto carolina, san miguel del padron, la habana
ClassifiedAddressOne(principal_street=['parque'],
                                          first_side_street=['carolina',],
                                          second_side_street=[],
                                          locality=['carolina'],
                                          municipality=['san', 'miguel', 'del', 'padron'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['calle', 'esq', 'avenida', ',', 'reparto', ',', ',']),
# calle san juan, guanabacoa, ciudad de la habana
ClassifiedAddressOne(principal_street=['san', 'juan'],
                                          first_side_street=[],
                                          second_side_street=[],
                                          locality=[],
                                          municipality=['guanabacoa',],
                                          province=['ciudad', 'de', 'la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['calle', ',', ',']),
# calle el brinco, santa fe, guanabacoa, ciudad de la habana
ClassifiedAddressOne(principal_street=['el', 'brinco'],
                                          first_side_street=[],
                                          second_side_street=[],
                                          locality=['santa', 'fe'],
                                          municipality=['guanabacoa',],
                                          province=['ciudad', 'de', 'la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['calle', ',', ',', ',']),
# san juan, guanabacoa, reparto bacuranao, ciudad de la habana
ClassifiedAddressOne(principal_street=['san', 'juan'],
                                          first_side_street=[],
                                          second_side_street=[],
                                          locality=['bacuranao'],
                                          municipality=['guanabacoa',],
                                          province=['ciudad', 'de', 'la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['reparto', ',', ',', ',']),
# esquina 3a y primera e, cuatro caminos, bejucal, la habana
ClassifiedAddressOne(principal_street=['3a'],
                                          first_side_street=['primera', 'e'],
                                          second_side_street=[],
                                          locality=['cuatro', 'caminos'],
                                          municipality=['bejucal',],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['esquina', 'y', ',', ',', ',']),
# maceo esquina 49 san jose de las lajas, la habana
ClassifiedAddressOne(principal_street=['maceo'],
                                          first_side_street=['49'],
                                          second_side_street=[],
                                          locality=[],
                                          municipality=['san', 'jose', 'de', 'las', 'lajas'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['esquina', ',']),
# calle sayas esq sandaio camblort san antonio de los baños, la habana
ClassifiedAddressOne(principal_street=['sayas'],
                                          first_side_street=['sandaio', 'camblort'],
                                          second_side_street=[],
                                          locality=[],
                                          municipality=['san', 'antonio', 'de', 'los', 'baños'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['calle', 'esq', ',']),

]

ADDRESS_LIST_EVAL_2 = [
# Pliar SN  e/  Julio de Cardenas y Lindero, Arroyo Naranjo, La Habana
ClassifiedAddressOne(principal_street=['Pliar'],
                                          first_side_street=['Julio', 'de', 'Cardenas'],
                                          second_side_street=['Lindero'],
                                          locality=[],
                                          municipality=['Arroyo', 'Naranjo'],
                                          province=['la', 'habana'],
                                          building=['SN'],
                                          apartment=[],
                                      reserve_word=['e/', 'y',',' ',']),
# 31 A e/ 320 y 322, La Lisa, La Habana
ClassifiedAddressOne(principal_street=['31', 'A'],
                                          first_side_street=['320'],
                                          second_side_street=['322'],
                                          locality=[],
                                          municipality=['La', 'Lisa'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',']),
# C  e/  Delicias y San Francisco, San  Miguel del Padron, La Habana
ClassifiedAddressOne(principal_street=['C'],
                                          first_side_street=['Delicias'],
                                          second_side_street=['San', 'Francisco'],
                                          locality=[],
                                          municipality=['San',  'Miguel', 'del', 'Padron'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',']),
# 39 e/ San Juan Bautista y Union, Plaza de la Revolucion, La Habana
ClassifiedAddressOne(principal_street=['39'],
                                          first_side_street=['San', 'Juan', 'Bautista'],
                                          second_side_street=['Union'],
                                          locality=[],
                                          municipality=['Plaza', 'de', 'la', 'Revolucion'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',']),
# Línea e/ 20 y 22, Vedado, Plaza de la Revolucion, La Habana
ClassifiedAddressOne(principal_street=['Línea'],
                                          first_side_street=['20'],
                                          second_side_street=['22'],
                                          locality=['Vedado'],
                                          municipality=['Plaza', 'de', 'la', 'Revolucion'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',', ',']),
# 1ra e/ D y E, reparto Luyano Moderno, San  Miguel del Padron, La Habana
ClassifiedAddressOne(principal_street=['1ra'],
                                          first_side_street=['D'],
                                          second_side_street=['E'],
                                          locality=['Luyano', 'Moderno'],
                                          municipality=['San',  'Miguel', 'del', 'Padron'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', 'reparto', ',', ',', ',']),
# 29 e/ 310 y 312, La Lisa, La Habana
ClassifiedAddressOne(principal_street=['29'],
                                          first_side_street=['310'],
                                          second_side_street=['312'],
                                          locality=[],
                                          municipality=['La', 'Lisa'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',']),
# 428 e/ 19 y 21, Pena altas, Guanabo, La Habana del Este, La Habana
ClassifiedAddressOne(principal_street=['428'],
                                          first_side_street=['19'],
                                          second_side_street=['21'],
                                          locality=['Pena altas', 'Guanabo'],
                                          municipality=['La Habana del Este'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',', ',', ',']),
# 246 e/ 33 C y 35, La Lisa, La Habana
ClassifiedAddressOne(principal_street=['246'],
                                          first_side_street=['33', 'C'],
                                          second_side_street=['35'],
                                          locality=[],
                                          municipality=['La', 'Lisa'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',']),
# Figura e/ Vives y Esperanza, La Habana Vieja, La Habana
ClassifiedAddressOne(principal_street=['Figura'],
                                          first_side_street=['Vives'],
                                          second_side_street=['Esperanza'],
                                          locality=[],
                                          municipality=['La', 'Habana', 'Vieja'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',']),
# B e/ 1 y 2, Mercedita, San Miguel del Padron, La Habana
ClassifiedAddressOne(principal_street=['B'],
                                          first_side_street=['1'],
                                          second_side_street=['2'],
                                          locality=['Mercedita'],
                                          municipality=['San', 'Miguel', 'del', 'Padron'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',', ',']),
# 161 e/ 310 y 314, Valle Brande, La Lisa, La Habana
ClassifiedAddressOne(principal_street=['161'],
                                          first_side_street=['310'],
                                          second_side_street=['314'],
                                          locality=['Valle', 'Brande'],
                                          municipality=['La', 'Lisa'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',', ',']),
# Santa Ana e/ Luco y Villanueva, Diez de Octubre, La Habana
ClassifiedAddressOne(principal_street=['Santa', 'Ana'],
                                          first_side_street=['Luco'],
                                          second_side_street=['Villanueva'],
                                          locality=[],
                                          municipality=['Diez', 'de', 'Octubre'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',']),
# 44 e/ 19 Y  21, Playa, La Habana
ClassifiedAddressOne(principal_street=['44'],
                                          first_side_street=['19'],
                                          second_side_street=['21'],
                                          locality=[],
                                          municipality=['playa'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',']),
#  Joaquin Delgado e Santa Clara y Esperanza, reparto Parraga, Arroyo Naranjo, La Habana
ClassifiedAddressOne(principal_street=['Joaquin', 'Delgado'],
                                          first_side_street=['Santa', 'Clara'],
                                          second_side_street=['Esperanza'],
                                          locality=['Parraga'],
                                          municipality=['Arroyo', 'Naranjo'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e', 'y', ',', 'reparto', ',', ',']),
# CALLE C  # 9512 A  /  6 y 10 Reparto Altahabana ,BOYEROS,La Habana
ClassifiedAddressOne(principal_street=['c'],
                                          first_side_street=['6'],
                                          second_side_street=['10'],
                                          locality=['Altahabana'],
                                          municipality=['BOYEROS'],
                                          province=['la', 'habana'],
                                          building=['9512'],
                                          apartment=['A'],
                                      reserve_word=['CALLE', '#', '/', 'y', 'Reparto', ',', ',']),
# Calle 160 No 4509E / Ave 45 y Ave 47,LA LISA,La Habana
ClassifiedAddressOne(principal_street=['160'],
                                          first_side_street=['45'],
                                          second_side_street=[47],
                                          locality=[],
                                          municipality=['LA', 'LISA'],
                                          province=['la', 'habana'],
                                          building=['4509E'],
                                          apartment=[],
                                      reserve_word=['Calle', 'No', '/', 'Ave', 'y', 'Ave', ',', ',']),
# Calle Maceo  # 61Alto entre Bertenati y Nazareno,PLAZA DE LA REVOLUCION,La Habana
ClassifiedAddressOne(principal_street=['Maceo'],
                                          first_side_street=['Bertenati'],
                                          second_side_street=['Nazareno'],
                                          locality=[],
                                          municipality=['PLAZA', 'DE', 'LA', 'REVOLUCION'],
                                          province=['la', 'habana'],
                                          building=['61Alto'],
                                          apartment=[],
                                      reserve_word=['Calle', '#', 'entre', 'y', ',', ',']),
# Destramoes  # 58 entre Luis esteves y Lacret, Santo Suarez,DIEZ DE OCTUBRE,La Habana
ClassifiedAddressOne(principal_street=['Destramoes'],
                                          first_side_street=['Luis', 'esteves'],
                                          second_side_street=['Lacret'],
                                          locality=['Santo', 'Suarez'],
                                          municipality=['DIEZ', 'DE', 'OCTUBRE'],
                                          province=['la', 'habana'],
                                          building=['58'],
                                          apartment=[],
                                      reserve_word=['#', 'entre', 'y', ',', ',', ',']),
# Calle Máximo Gómez  # 264 Altos  E / 27 DE Noviembre y Pereira,REGLA,La Habana
ClassifiedAddressOne(principal_street=['Máximo', 'Gómez'],
                                          first_side_street=['27', 'DE', 'Noviembre'],
                                          second_side_street=['Pereira'],
                                          locality=[],
                                          municipality=['REGLA'],
                                          province=['la', 'habana'],
                                          building=['264'],
                                          apartment=[],
                                      reserve_word=['Calle', '#', 'Altos', 'E', '/', 'y', ',', ',']),
# Calle San Mariano  # 761 entre San Juan Bosco y Graciela apto 8, Vibora,DIEZ DE OCTUBRE,La Habana
ClassifiedAddressOne(principal_street=['San', 'Mariano'],
                                          first_side_street=['San', 'Juan', 'Bosco'],
                                          second_side_street=['Graciela'],
                                          locality=['Vibora'],
                                          municipality=['DIEZ', 'DE', 'OCTUBRE'],
                                          province=['la', 'habana'],
                                          building=['761'],
                                          apartment=['8'],
                                      reserve_word=['Calle', '#', 'entre', 'y', 'apto', ',', ',', ',']),
# Calle 111 E / cALLE 24 y Calle 24 A Edificio 6 apt 4 Reparto Sierra Maestra,BOYEROS,La Habana
ClassifiedAddressOne(principal_street=['111'],
                                          first_side_street=['24'],
                                          second_side_street=['24', 'A'],
                                          locality=['Sierra', 'Maestra'],
                                          municipality=['BOYEROS'],
                                          province=['la', 'habana'],
                                          building=['6'],
                                          apartment=['4'],
                                      reserve_word=['Calle', 'E', '/', 'cALLE', 'y', 'Calle', 'Edificio', 'apt', 'Reparto', ',', ',']),
# Calle Barbería e /  Calle Universidad y Calle Estevez edf 32 apto 4,CERRO,La Habana
ClassifiedAddressOne(principal_street=['Barbería'],
                                          first_side_street=['Universidad'],
                                          second_side_street=['Estevez'],
                                          locality=[],
                                          municipality=['CERRO'],
                                          province=['la', 'habana'],
                                          building=['32'],
                                          apartment=['4'],
                                      reserve_word=['Calle', 'e', '/',  'Calle', 'y', 'Calle', 'edf', 'apto', ',', ',']),
# CALLE 18  #  505 BAJO ENTRE CONCEPCION Y SAN FRANCISCO LAWTON,DIEZ DE OCTUBRE,La Habana
ClassifiedAddressOne(principal_street=['18'],
                                          first_side_street=['CONCEPCION'],
                                          second_side_street=['SAN', 'FRANCISCO'],
                                          locality=[],
                                          municipality=['DIEZ', 'DE', 'OCTUBRE'],
                                          province=['la', 'habana'],
                                          building=['505'],
                                          apartment=[],
                                      reserve_word=['CALLE', '#', 'BAJO', 'ENTRE', 'Y', ',', ',']),
# 180  #  42109 ENTRE 421 Y 423, LA AURORA,BOYEROS,La Habana
ClassifiedAddressOne(principal_street=['180'],
                                          first_side_street=['421'],
                                          second_side_street=['423'],
                                          locality=['LA', 'AURORA'],
                                          municipality=['BOYEROS'],
                                          province=['la', 'habana'],
                                          building=['42109'],
                                          apartment=[],
                                      reserve_word=['#', 'ENTRE', 'Y', ',', ',', ',']),
# Calle Gertrudis Oeste  # 459 E /  Anita y Goicuria Repto Sevillano,DIEZ DE OCTUBRE,La Habana
ClassifiedAddressOne(principal_street=['Gertrudis', 'Oeste'],
                                          first_side_street=['Anita'],
                                          second_side_street=['Goicuria'],
                                          locality=['Sevillano'],
                                          municipality=['DIEZ', 'DE', 'OCTUBRE'],
                                          province=['la', 'habana'],
                                          building=['459'],
                                          apartment=[],
                                      reserve_word=['Calle', '#', 'E', '/', 'Repto', ',', ',']),
# Avenida Santa Catalina e / Mayia Rodriguez  y La Sola,Edificio616,Apto 3,Reparto Santos Suarez,DIEZ DE OCTUBRE,La Habana
ClassifiedAddressOne(principal_street=['Santa', 'Catalina'],
                                          first_side_street=['Mayia', 'Rodriguez'],
                                          second_side_street=['La', 'Sola'],
                                          locality=['Santos', 'Suarez'],
                                          municipality=['DIEZ', 'DE', 'OCTUBRE'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=['3'],
                                      reserve_word=['Avenida', 'e', '/', 'y', 'Edificio616', 'Apto', ',', 'Reparto', ',', ',', ',']),
# Calle Pinar  # 8003 E / Santa Teresa y Collazo,Reparto Ponce,ARROYO NARANJO,La Habana
ClassifiedAddressOne(principal_street=['Pinar'],
                                          first_side_street=['Santa', 'Teresa'],
                                          second_side_street=['Collazo'],
                                          locality=['Ponce'],
                                          municipality=['ARROYO', 'NARANJO'],
                                          province=['la', 'habana'],
                                          building=['8003'],
                                          apartment=[],
                                      reserve_word=['Calle', '#', 'e', '/', 'y', ',', 'Reparto', ',', ',']),
# Avenida Ciudamar  # 17521 e /  Calle 13 y Calle 15, Reparto Ciudamar,SAN MIGUEL DEL PADRON,La Habana
ClassifiedAddressOne(principal_street=['Ciudamar'],
                                          first_side_street=['13'],
                                          second_side_street=['15'],
                                          locality=['Ciudamar'],
                                          municipality=['SAN', 'MIGUEL', 'DEL', 'PADRON'],
                                          province=['la', 'habana'],
                                          building=['17521'],
                                          apartment=[],
                                      reserve_word=['Avenida', '#', 'e', '/', 'Calle', 'y', 'Calle', ',', 'Reparto', ',', ',']),
# Calzada de 10 de Octubre  # 1155 apto1 e /  Santa Catalina y San Mariano,DIEZ DE OCTUBRE,La Habana
ClassifiedAddressOne(principal_street=['Calzada de 10 de Octubre'],
                                          first_side_street=['Santa', 'Catalina'],
                                          second_side_street=['San', 'Mariano'],
                                          locality=[],
                                          municipality=['DIEZ', 'DE', 'OCTUBRE'],
                                          province=['la', 'habana'],
                                          building=['1155'],
                                          apartment=[],
                                      reserve_word=['#', 'apto1', 'e', '/', 'y', ',', ',']),
# Calle 5ta B  #  9606 2 int,entre calle 96 y 98, Barrio Querejeta,PLAYA,La Habana
ClassifiedAddressOne(principal_street=['5ta', 'B'],
                                          first_side_street=['96'],
                                          second_side_street=['98'],
                                          locality=['Querejeta'],
                                          municipality=['PLAYA'],
                                          province=['la', 'habana'],
                                          building=['9606'],
                                          apartment=['2'],
                                      reserve_word=['Calle', '#', 'int', ',', 'entre', 'calle', 'y', ',', ',' ,',', 'Barrio']),
# Calle 1 No  17416 E / Calle A y Calle San Luis,Reparto Encanto,SAN MIGUEL DEL PADRON,La Habana
ClassifiedAddressOne(principal_street=['1'],
                                          first_side_street=['A'],
                                          second_side_street=['San', 'Luis'],
                                          locality=['Encanto'],
                                          municipality=['SAN', 'MIGUEL', 'DEL', 'PADRON'],
                                          province=['la', 'habana'],
                                          building=['17416'],
                                          apartment=[],
                                      reserve_word=['Calle', 'No', 'e', '/', 'Calle', 'y', 'Calle', ',', 'Reparto', ',', ',']),
# Calle 9na  # 14 ,Apto 3 E / Calle E y Calle D,Barrio Lawton,DIEZ DE OCTUBRE,La Habana
ClassifiedAddressOne(principal_street=['9na'],
                                          first_side_street=['E'],
                                          second_side_street=['D'],
                                          locality=['Lawton'],
                                          municipality=['DIEZ', 'DE', 'OCTUBRE'],
                                          province=['la', 'habana'],
                                          building=['14'],
                                          apartment=['3'],
                                      reserve_word=['Calle', '#', ',', 'Apto', 'E', '/', 'Calle', 'y', 'Calle', ',', 'Barrio', ',', ',']),
# Calle Tenerifr # 156 apto  6 E /  Rastro y Carmen  ,CENTRO HABANA,La Habana
ClassifiedAddressOne(principal_street=['Tenerifr'],
                                          first_side_street=['Rastro'],
                                          second_side_street=['Carmen'],
                                          locality=[],
                                          municipality=['CENTRO', 'HABANA'],
                                          province=['la', 'habana'],
                                          building=['156'],
                                          apartment=['6'],
                                      reserve_word=['Calle', '#', 'apto', 'E', '/', 'y', ',', ',']),
# Ave Entrada E / Ave de los Ocujes y Ave  de la Ceiba Edificio 2 APTO 5 Reparto Santa Catalina,CERRO,La Habana
ClassifiedAddressOne(principal_street=['Entrada'],
                                          first_side_street=['Ave de los Ocujes'],
                                          second_side_street=['Ave', 'de', 'la', 'Ceiba'],
                                          locality=['Santa', 'Catalina'],
                                          municipality=['CERRO'],
                                          province=['la', 'habana'],
                                          building=['2'],
                                          apartment=['5'],
                                      reserve_word=['Ave', 'E', '/', 'y', 'Edificio', 'APTO', 'Reparto', ',', ',']),
# Sta Catalina e / Vento y San Juán Bosco ed 817 Y 819 apto 4,DIEZ DE OCTUBRE,La Habana
# ClassifiedAddressOne(principal_street=['Sta', 'Catalina'],
#                                           first_side_street=['Vento'],
#                                           second_side_street=[San Juán Bosco],
#                                           locality=[],
#                                           municipality=[''],
#                                           province=['la', 'habana'],
#                                           building=[],
#                                           apartment=[],
#                                       reserve_word=['e', '/', 'y', 'ed', ]),
# Aliados e/ Pasaje D y Central, San Miguel del Padron, La Habana
ClassifiedAddressOne(principal_street=['Aliados'],
                                          first_side_street=['D'],
                                          second_side_street=['Central'],
                                          locality=[],
                                          municipality=['San', 'Miguel', 'del', 'Padron'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'Pasaje', 'y', ',', ',']),
# Estancia e/ San Pedro y Lombill, Nuevo Vedado, Plaza de la Revolucion, La Habana
ClassifiedAddressOne(principal_street=['Estancia'],
                                          first_side_street=['San Pedro'],
                                          second_side_street=['Lombill'],
                                          locality=['Nuevo', 'Vedado'],
                                          municipality=['Plaza', 'de', 'la', 'Revolucion'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',', ',']),
# Estrella e/ Aguila y Angeles, Centro Habana, La Habana
ClassifiedAddressOne(principal_street=['Estrella'],
                                          first_side_street=['Aguila'],
                                          second_side_street=['Angeles'],
                                          locality=[],
                                          municipality=['Centro', 'Habana'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',']),
# Virginia e/ Pinar del Rio y Woodbury, reparto Callejas, Arroyo Naranjo, La Habana
ClassifiedAddressOne(principal_street=['Virginia'],
                                          first_side_street=['Pinar', 'del', 'Rio'],
                                          second_side_street=['Woodbury'],
                                          locality=['Callejas'],
                                          municipality=['Arroyo', 'Naranjo'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', 'reparto', ',', ',', ',']),
# Recurso e/ Masarredo y Lindero, Nuevo Vedado, Plaza de la Revolucion, La Habana
ClassifiedAddressOne(principal_street=['Recurso'],
                                          first_side_street=['Masarredo'],
                                          second_side_street=['Lindero'],
                                          locality=['Nuevo', 'Vedado'],
                                          municipality=['Plaza', 'de', 'la', 'Revolucion'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',', ',']),
# San Quintin e/ Salvador y Cerezo, Cerro, La Habana
ClassifiedAddressOne(principal_street=['San', 'Quintin'],
                                          first_side_street=['Salvador'],
                                          second_side_street=['Cerezo'],
                                          locality=[],
                                          municipality=['Cerro'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['e/', 'y', ',', ',']),
# Calle 6ta entre 16 y 17 Edificio 37 Apto 29 Reparto Guiteras  LA HABANA DEL ESTE La Habana
ClassifiedAddressOne(principal_street=['6ta'],
                                          first_side_street=['16'],
                                          second_side_street=['17'],
                                          locality=['Guiteras'],
                                          municipality=['LA', 'HABANA', 'DEL', 'ESTE'],
                                          province=['la', 'habana'],
                                          building=['37'],
                                          apartment=['29'],
                                      reserve_word=['Calle', 'entre', 'y', 'Edificio', 'Apto', 'Reparto']),
# Calle 308   1904A entre 19 y 21 Reparto Santa Fe  PLAYA La Habana
ClassifiedAddressOne(principal_street=['308'],
                                          first_side_street=['19'],
                                          second_side_street=['21'],
                                          locality=['Santa', 'Fe'],
                                          municipality=['PLAYA'],
                                          province=['la', 'habana'],
                                          building=['1904A'],
                                          apartment=[],
                                      reserve_word=['Calle', 'entre', 'y', 'Reparto']),
# Calle Santa Rosa     8 e entre San Antonio y Rizo  PLaza PLAZA DE LA REVOLUCION La Habana
ClassifiedAddressOne(principal_street=['Santa', 'Rosa'],
                                          first_side_street=['San', 'Antonio'],
                                          second_side_street=['Rizo'],
                                          locality=['PLaza'],
                                          municipality=['PLAZA', 'DE', 'LA', 'REVOLUCION'],
                                          province=['la', 'habana'],
                                          building=['8'],
                                          apartment=['e'],
                                      reserve_word=['Calle', 'entre', 'y']),
# Calle 17    853 e entre  4 y 6 PLAZA DE LA REVOLUCION La Habana
ClassifiedAddressOne(principal_street=['17'],
                                          first_side_street=['4'],
                                          second_side_street=['6'],
                                          locality=[],
                                          municipality=['PLAZA', 'DE', 'LA', 'REVOLUCION'],
                                          province=['la', 'habana'],
                                          building=['853'],
                                          apartment=['e'],
                                      reserve_word=['Calle', 'entre', 'y']),
# 67A No 11404 e 114 y 116 MARIANAO La Habana
ClassifiedAddressOne(principal_street=['67A'],
                                          first_side_street=['114'],
                                          second_side_street=['116'],
                                          locality=[],
                                          municipality=['MARIANAO'],
                                          province=['la', 'habana'],
                                          building=['11404'],
                                          apartment=[],
                                      reserve_word=['No', 'e', 'y']),
# Calle 203 entre 290 y Prensa Latina, Poblado Pueblo del Chico, BOYEROS, La Habana
ClassifiedAddressOne(principal_street=[''],
                                          first_side_street=['290'],
                                          second_side_street=['Prensa', 'Latina'],
                                          locality=['Pueblo', 'del', 'Chico'],
                                          municipality=['BOYEROS'],
                                          province=['la', 'habana'],
                                          building=[],
                                          apartment=[],
                                      reserve_word=['Calle', 'entre', 'y', ',', 'Poblado', ',', ',']),
]